/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzleproject;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author az
 */
public class start extends javax.swing.JFrame {

    ImageIcon ic;
    JButton b, b2;

    /**
     * Creates new form start
     */
    public start() {
        ic = new ImageIcon(getClass().getResource("e0.JPG"));
        b = new JButton(ic);
        b2 = new JButton(" PLAY ");
        b2.setSize(300, 300);
        b.setSize(550, 600);
        event e = new event();
        b2.addActionListener(e);
        b.add(b2);
        add(b);
    }

    class event implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            jigsaw obj = new jigsaw();
            obj.setVisible(true);
            obj.setSize(600, 600);
            dispose();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        start obj = new start();
        obj.setVisible(true);
        obj.setSize(600, 600);
        obj.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
